services:
  app:
    build: .
    container_name: shortener-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/shortener
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=secret
      - APP_BASE-URL=http://localhost:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: shortener-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: